server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: top.rocyuan.entity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/roc_springboot
    username: root
    password: root
